### ISSUE TITLE
Research: Increase Analytics Controller Load time

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#222] opened 2015-12-08 08:48 UTC
Currently, it takes about 20 seconds (on easol-dev) for analytics to load. On local machines it can take up to a minute or more.

We are thinking how to increase the load time. Actually, the timing became higher after we integrated client level filtering everywhere. Now it is loading all data at once, and before it was only loading data for one year. I'm thinking, maybe it would be possible to add (only for this controller) AJAX load or something similar?

The problem is only for the main screen. Where we have to do API calls for every of the section. And every call before that needs a number of SQL queries.

All other suggestions how to make it work quicker are welcome!

**Comment by ciprogrammer** [comment] 2015-12-08 09:24
SQL can query "hundreds of thousands"/millions of records instantly so a ~20 second query time on the same machine as the db suggests slow queries being the problem. I would investigate the server loads and available resources first, followed by a query analysis to see why it takes so long to query such a small record set. If the slow page uses API calls then those speeds need to be studied as well to see if they cause the bottleneck. If the server, db, and api calls are not to blame then I would consider an AJAX based solution for smaller record sets but this shouldn't be needed.

**Comment by jasonhoekstra** [comment] 2015-12-08 13:09
From @ciprogrammer's comment above, we may want to use Query Analyzer or similar to evaluate the query run plan.  Given our custom query to retrieve the data, creating some additional indexes may improve query performance.

**Comment by regiscamimura** [comment] 2015-12-08 18:12
I think we have room to improve the queries there. We might want to try to use subqueries instead of running large queries inside a loop on top a result of another large query. 
But I believe the major problem here is that we're doing several different requests to the API inside the loop. So we first run a query, and for each result row, we're running another queries, and based on the result of both, we send a request to the API to the individual records. 

I actually think the queries are pretty fast, but let's say the queries might be taking a bit to process. Still, it could never take more than doing the API requests. 

Right now, we have around 120 synchronously API requests, I mean, the code workflow is iterating over 120 records, and before moving to the next one, it needs to first get the response of the previous one. I'm pretty much sure that's the cause of the delay.

The current logic is:

1. Retrieve sections 
2. Retrieve meeting times for each section
3. Retrieve students related to the sections

4. For each section, trigger a request to the API where the parameters are each student's ID, the start meeting time and end meeting time. 

Said that, I need to know more details from the API. It would be possible that the API has a function that returns data across all the start/end meeting time? Indirectly, we would be retrieving data related to ALL sections at once, in a single request, through the meeting time. If that's possible, we can modify the code to do that single request, and separate the data properly in our side. 

I strongly believe the API can do that, we would just expand the start/end time parameters to the min and max values in the set. 

Anyway, if the API can NOT to that, or if the single request still takes too long to process, then we can use AJAX to do the API requests. 

=================

Estimate for doing the single request change is 12h or so in a rough estimate. I need to get some more details on the API to provide an accurate estimate though. I need to get some specs on the parameters and the responses. Where can I get that?

**Comment by edgarf** [comment] 2015-12-08 21:25
@regiscamimura - that might be a really good idea - to have one API call with all meeting times. The API documentation is here https://www.dropbox.com/s/94euwyt7y6an2rt/ANALYTICS_API_DOCUMENTATION.yaml.txt?dl=0
Just load the data into here - http://editor.swagger.io/#/
I will then also think if this method wouldn't present any other issues and then discuss with Jason if we can implement it. Meanwhile, if you have time, please take a look at the documentation to see if it's possible to be done. However, as far as I see - should be possible.

**Comment by ciprogrammer** [comment] 2015-12-09 08:58
If it ends up that the synchronous api requests are the bottleneck and the api cant do what has been suggested here then you could always pass the sections/meeting times/students to the view and leverage the javascript to do the api calls asynchronously and do the api response date manipulations client side if they are not too involved. You could use a loading... animated gif as a placeholder while the client handles the api calls. This solution's viability is dependent on the api's ability to process multiple requests simultaneously, of course.

**Comment by edgarf** [comment] 2015-12-09 19:21
Thanks for your input @ciprogrammer  and @regiscamimura. For now we are going to postpone this task and bring it back a little bit later. Thanks anyways, putting it into the icebox for now.

**Closed** 2016-04-13 14:46 UTC
